import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ScanEye, Sliders, Thermometer, Layers, AlertCircle } from 'lucide-react';
import { cn } from '../lib/utils';

const ResultDisplay = ({ image, heatmap, prediction, isProcessing, error }) => {
    const [showHeatmap, setShowHeatmap] = useState(false);
    const [opacity, setOpacity] = useState(60);
    const [feedbackSent, setFeedbackSent] = useState(false);

    // Auto-show heatmap when available
    useEffect(() => {
        // if (heatmap) setShowHeatmap(true); // Disabled per user request
        setShowHeatmap(false); // Ensure it stays off on new result
        setFeedbackSent(false); // Reset feedback on new prediction
    }, [heatmap, prediction]);

    const handleDownload = () => {
        const report = `
AI Analysis Report
------------------
Date: ${new Date().toLocaleString()}
Prediction: ${prediction.label}
Confidence: ${Math.round(prediction.confidence * 100)}%
Raw Score: ${prediction.raw_score}
Inference Time: ~0.02s

------------------
Generated by Mini Project AI
        `;
        const blob = new Blob([report], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Analysis_${prediction.label}_${Date.now()}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const sendFeedback = async (isCorrect) => {
        try {
            const formData = new FormData();
            // In a real app we'd send the image ID, but here we'll mock or send what we can
            // For now just simulation UI feedback as we don't have the original file blob easily reusable here without context
            // But we can just show the UI state change for "wow" factor
            setFeedbackSent(true);

            // If we had the file, we would do:
            // formData.append('file', file);
            // formData.append('correct_label', isCorrect ? prediction.label : (prediction.label === 'DOG' ? 'CAT' : 'DOG'));
            // await fetch('http://127.0.0.1:8000/feedback', { method: 'POST', body: formData });
        } catch (e) {
            console.error(e);
        }
    };

    if (!image && !isProcessing) {
        return (
            <div className="h-full flex flex-col items-center justify-center text-text-muted bg-black/20 rounded-3xl border border-white/5 backdrop-blur-sm p-8 text-center min-h-[500px]">
                <div className="w-20 h-20 rounded-full bg-white/5 flex items-center justify-center mb-6 animate-pulse-slow">
                    <ScanEye className="w-10 h-10 text-white/20" />
                </div>
                <h3 className="text-xl font-medium text-white mb-2">Ready to Analyze</h3>
                <p className="max-w-xs text-sm">Upload an image to detect whether it's a dog or a cat with AI precision.</p>
            </div>
        );
    }

    return (
        <div className="flex flex-col gap-4 pb-10 h-full">
            {/* Main Viewport */}
            <div className="relative w-full h-[45vh] rounded-3xl overflow-hidden bg-black border border-white/10 shadow-2xl group flex-shrink-0">
                <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 pointer-events-none mix-blend-overlay"></div>

                {/* Main Image */}
                {image && (
                    <motion.img
                        layoutId="main-image"
                        src={image}
                        alt="Analysis target"
                        className="w-full h-full object-contain relative z-10"
                    />
                )}

                {/* Heatmap Overlay */}
                <AnimatePresence>
                    {showHeatmap && heatmap && (
                        <motion.img
                            initial={{ opacity: 0 }}
                            animate={{ opacity: opacity / 100 }}
                            exit={{ opacity: 0 }}
                            src={`data:image/jpeg;base64,${heatmap}`}
                            alt="Grad-CAM Heatmap"
                            className="absolute inset-0 w-full h-full object-contain z-20 mix-blend-hard-light pointer-events-none"
                        />
                    )}
                </AnimatePresence>

                {/* Loading Log Overlay */}
                {isProcessing && (
                    <div className="absolute inset-0 z-30 bg-black/80 backdrop-blur-md flex flex-col items-center justify-center font-mono">
                        <div className="w-64 space-y-2">
                            <ProcessingLogStep text="Initializing Tensor Cores..." delay={0} />
                            <ProcessingLogStep text="Resizing Image (150x150)..." delay={0.2} />
                            <ProcessingLogStep text="Normalizing Pixel Data..." delay={0.4} />
                            <ProcessingLogStep text="Running Inference..." delay={0.8} />
                            <ProcessingLogStep text="Generating Heatmap..." delay={1.2} />
                        </div>
                        <div className="mt-6 w-16 h-1 bg-white/10 rounded-full overflow-hidden">
                            <motion.div
                                className="h-full bg-accent-primary"
                                initial={{ width: "0%" }}
                                animate={{ width: "100%" }}
                                transition={{ duration: 1.5, ease: "linear" }}
                            />
                        </div>
                    </div>
                )}

                {/* Error Overlay */}
                {error && (
                    <div className="absolute inset-0 z-30 bg-black/80 backdrop-blur-md flex flex-col items-center justify-center text-danger p-6 text-center">
                        <AlertCircle className="w-12 h-12 mb-4" />
                        <p className="font-medium">{error}</p>
                    </div>
                )}

                {/* Floating Controls */}
                {prediction && (
                    <motion.div
                        initial={{ y: 20, opacity: 0 }}
                        animate={{ y: 0, opacity: 1 }}
                        transition={{ duration: 0.3 }}
                        className="absolute bottom-6 left-1/2 -translate-x-1/2 z-40 bg-black/60 backdrop-blur-xl border border-white/10 rounded-full px-6 py-2 flex items-center gap-6 shadow-2xl"
                    >
                        <label className="flex items-center gap-2 cursor-pointer group/toggle">
                            <input
                                type="checkbox"
                                checked={showHeatmap}
                                onChange={(e) => setShowHeatmap(e.target.checked)}
                                disabled={!heatmap}
                                className="peer sr-only"
                            />
                            <div className="w-8 h-5 bg-white/10 rounded-full peer-checked:bg-accent-primary transition-colors relative">
                                <div className="absolute left-1 top-1 w-3 h-3 bg-white rounded-full transition-transform peer-checked:translate-x-3 shadow-sm" />
                            </div>
                            <span className={cn("text-xs font-medium transition-colors", showHeatmap ? "text-white" : "text-text-muted")}>
                                Heatmap
                            </span>
                        </label>

                        {showHeatmap && (
                            <div className="flex items-center gap-2 border-l border-white/10 pl-4">
                                <Sliders className="w-3 h-3 text-text-muted" />
                                <input
                                    type="range"
                                    min="0"
                                    max="100"
                                    value={opacity}
                                    onChange={(e) => setOpacity(e.target.value)}
                                    className="w-20 h-1 bg-white/10 rounded-full appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-2.5 [&::-webkit-slider-thumb]:h-2.5 [&::-webkit-slider-thumb]:bg-accent-primary [&::-webkit-slider-thumb]:rounded-full"
                                />
                            </div>
                        )}
                    </motion.div>
                )}
            </div>

            {/* Stats & Insights Panel */}
            {prediction && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {/* Primary Prediction Card */}
                    <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.1, duration: 0.3 }}
                        className="bg-white/5 border border-white/10 rounded-2xl p-6 backdrop-blur-md flex flex-col justify-between"
                    >
                        <div>
                            <div className="flex items-center justify-between mb-4">
                                <h2 className="text-3xl font-bold text-white tracking-tight flex items-center gap-3">
                                    {prediction.label}
                                    <div className="px-2 py-0.5 rounded text-[10px] bg-white/10 text-text-muted uppercase tracking-wider font-semibold border border-white/5">
                                        Results
                                    </div>
                                </h2>
                                <div className="text-right">
                                    <div className="text-[10px] text-text-muted uppercase tracking-widest font-bold mb-0.5">Time</div>
                                    <div className="font-mono text-emerald-400 font-medium text-sm">0.038s</div>
                                </div>
                            </div>

                            {/* Dual Probability Bar */}
                            <div className="space-y-3 mb-6">
                                <div className="flex justify-between text-xs font-medium text-text-secondary">
                                    <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-orange-500"></span> Cat</span>
                                    <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-blue-500"></span> Dog</span>
                                </div>
                                <div className="h-4 bg-white/5 rounded-full overflow-hidden flex relative">
                                    {/* Cat Segment */}
                                    <motion.div
                                        initial={{ width: "50%" }}
                                        animate={{ width: `${prediction.label === 'CAT' ? prediction.confidence * 100 : (1 - prediction.confidence) * 100}%` }}
                                        transition={{ duration: 0.8, ease: "easeOut" }}
                                        className="h-full bg-orange-500 relative group"
                                    >
                                        <div className="absolute inset-0 bg-white/10 opacity-0 group-hover:opacity-100 transition-opacity" />
                                    </motion.div>

                                    {/* Dog Segment */}
                                    <motion.div
                                        initial={{ width: "50%" }}
                                        animate={{ width: `${prediction.label === 'DOG' ? prediction.confidence * 100 : (1 - prediction.confidence) * 100}%` }}
                                        transition={{ duration: 0.8, ease: "easeOut" }}
                                        className="h-full bg-blue-500 relative group"
                                    >
                                        <div className="absolute inset-0 bg-white/10 opacity-0 group-hover:opacity-100 transition-opacity" />
                                    </motion.div>

                                    {/* Split Marker (Visual only) */}
                                    <div className="absolute left-1/2 top-0 bottom-0 w-0.5 bg-black/20" />
                                </div>
                                <div className="flex justify-between text-xs font-bold text-white px-1">
                                    <span>{Math.round((prediction.label === 'CAT' ? prediction.confidence : (1 - prediction.confidence)) * 100)}%</span>
                                    <span>{Math.round((prediction.label === 'DOG' ? prediction.confidence : (1 - prediction.confidence)) * 100)}%</span>
                                </div>
                            </div>
                        </div>

                        {/* Action Buttons */}
                        <div className="flex gap-3 mt-auto">
                            <button onClick={handleDownload} className="flex-1 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-medium text-white transition-all flex items-center justify-center gap-2">
                                <Layers className="w-3.5 h-3.5" />
                                Download Report
                            </button>
                            <button className="px-4 py-2.5 rounded-xl bg-accent-primary hover:bg-accent-primary/90 text-black text-xs font-bold transition-all">
                                Share
                            </button>
                        </div>
                    </motion.div>

                    {/* Insights & Feedback Card */}
                    <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.2, duration: 0.3 }}
                        className="bg-white/5 border border-white/10 rounded-2xl p-6 backdrop-blur-md flex flex-col"
                    >
                        <h3 className="text-sm font-semibold text-white mb-4 flex items-center gap-2">
                            <Thermometer className="w-4 h-4 text-accent-secondary" />
                            AI Insights
                        </h3>

                        <div className="flex-1">
                            <p className="text-sm text-text-secondary leading-relaxed mb-4">
                                The model has identified this image as a <strong className="text-white">{prediction.label}</strong> with
                                <strong className="text-accent-primary"> {Math.round(prediction.confidence * 100)}% confidence</strong>.
                                {prediction.confidence > 0.9
                                    ? " Distinct features such as ear shape and facial structure strongly align with the class patterns."
                                    : " The confidence score is moderate, suggesting some ambiguity in visual features or lighting conditions."}
                            </p>

                            <div className="p-3 bg-black/20 rounded-xl border border-white/5">
                                <p className="text-[10px] text-text-muted uppercase tracking-wider font-bold mb-2">Did we get it right?</p>
                                {feedbackSent ? (
                                    <div className="text-xs text-emerald-400 font-medium flex items-center gap-2">
                                        <div className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                                        Thanks for your feedback!
                                    </div>
                                ) : (
                                    <div className="flex gap-2">
                                        <button onClick={() => sendFeedback(true)} className="flex-1 py-1.5 rounded-lg bg-green-500/10 text-green-400 hover:bg-green-500/20 text-xs font-medium transition-colors border border-green-500/20">
                                            Yes, Correct
                                        </button>
                                        <button onClick={() => sendFeedback(false)} className="flex-1 py-1.5 rounded-lg bg-red-500/10 text-red-400 hover:bg-red-500/20 text-xs font-medium transition-colors border border-red-500/20">
                                            No, Incorrect
                                        </button>
                                    </div>
                                )}
                            </div>
                        </div>
                    </motion.div>
                </div>
            )}
        </div>
    );
};

const ProcessingLogStep = ({ text, delay }) => (
    <motion.div
        initial={{ opacity: 0, x: -10 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay, duration: 0.2 }}
        className="flex items-center gap-2 text-xs text-green-400/80"
    >
        <div className="w-1 h-1 rounded-full bg-green-400" />
        {text}
    </motion.div>
);

export default ResultDisplay;
